/**
 * Permanent integration of Cervantes for the Vauban container (MicroProfile JWT 2.1 §CDI).
 *
 * <p>Provides the main {@code @RequestScoped JsonWebToken} of the current query (powered)
 * by the {@link io.vidocq.cervantes.cdi.JsonWebTokenContext} context, placed by the filter
 * and produces a {@code JwtValidator} configured from the
 * properties MicroProfile Config {@code mp.jwt.verify.*} (via Ravel).</p>
 *
 * <p>Note JPMS — workaround testCompile: {@code module-info.java} in {@code src/main/module-info/}
 * (vauban-core/level-core are test-scope, absent from the path module). See ZZPH0ZZ.ZZPH1ZZ
 */
module io.vidocq.cervantes.cdi.vauban {
    requires transitive io.vidocq.cervantes.core;
    requires org.eclipse.microprofile.config;

    requires static jakarta.cdi;
    requires static jakarta.inject;
    requires static jakarta.annotation;
    // Compile-only (optional at runtime): supplies the VaubanComponentProvider service type.
    // Absent under Weld — the provides below is then inert (nobody `uses` it).
    requires static io.vidocq.vauban.api;

    provides jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension
            with io.vidocq.cervantes.cdi.CervantesClaimExtension;

    // In-module instantiation, field injection AND method invocation of this module's beans,
    // contexts and producers — generated by the vauban-maven-plugin as one _VaubanComponents per
    // package (co-located so each can reach its package's package-private members). The container
    // therefore needs no reflection and no `opens … to io.vidocq.vauban.core` for them.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.cervantes.cdi._VaubanComponents,
                 io.vidocq.cervantes.cdi.internal._VaubanComponents;

    exports io.vidocq.cervantes.cdi;
    exports io.vidocq.cervantes.cdi.internal;
    // No `opens … to io.vidocq.vauban.core`: the BCE is loaded via ServiceLoader (provides above),
    // JsonWebTokenContext is instantiated in-module by the .cdi provider, and the .internal producer
    // beans (JsonWebTokenProducer, JwtAuthConfigProducer) are instantiated and their @Produces
    // methods invoked in-module by the .internal provider — all without deep reflection.
}
