/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
/**
 * Cervantes CDI integration for the Vauban container (MicroProfile JWT 2.2 §CDI).
 *
 * <p>Provides the {@code @RequestScoped JsonWebToken} principal of the current request (fed
 * by the {@link io.vidocq.cervantes.cdi.JsonWebTokenContext} context, set by the JAX-RS
 * authentication filter) and produces a {@code JwtValidator} configured from the
 * MicroProfile Config properties {@code mp.jwt.verify.*} (via Ravel).</p>
 */
module io.vidocq.cervantes.cdi.vauban {
    requires transitive io.vidocq.cervantes.core;
    requires org.eclipse.microprofile.config;
    // ClaimResolver maps claims to JSON-P values; cervantes-core reads jakarta.json non-transitively.
    requires jakarta.json;

    requires static jakarta.cdi;
    requires static jakarta.inject;
    requires static jakarta.annotation;
    // Compile-only (optional at runtime): supplies the VaubanComponentProvider service type.
    // Absent under Weld — the provides below is then inert (nobody `uses` it).
    requires static io.vidocq.vauban.api;

    // Looked up to tell "no MicroProfile Config implementation" from a Config that fails to boot.
    uses org.eclipse.microprofile.config.spi.ConfigProviderResolver;

    provides jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension
            with io.vidocq.cervantes.cdi.CervantesClaimExtension;

    // In-module instantiation, field injection AND method invocation of this module's beans,
    // contexts and producers — generated by the vauban-maven-plugin as one _VaubanComponents per
    // package (co-located so each can reach its package's package-private members). The container
    // therefore needs no reflection and no `opens … to io.vidocq.vauban.core` for them.
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.cervantes.cdi._VaubanComponents,
                 io.vidocq.cervantes.cdi.internal._VaubanComponents;

    exports io.vidocq.cervantes.cdi;
    exports io.vidocq.cervantes.cdi.internal;
    // No `opens … to io.vidocq.vauban.core`: the BCE is loaded via ServiceLoader (provides above),
    // JsonWebTokenContext is instantiated in-module by the .cdi provider, and the .internal producer
    // beans (JsonWebTokenProducer, JwtAuthConfigProducer) are instantiated and their @Produces
    // methods invoked in-module by the .internal provider — all without deep reflection.
}
